- name: Create a temporary admin user for maintenance
  hosts: nucs
  become: yes
  tasks:
    - name: Check for existence of the tempadmin user
      command: id tempadmin
      register: tempadmin_check
      changed_when: false
      failed_when: tempadmin_check.rc not in [0, 1]

    - name: Create a temporary user with sudo privileges
      user:
        name: tempadmin
        state: present
        create_home: yes
        groups: sudo
      when: tempadmin_check.rc == 1

    - name: Set authorized key for the temporary user from the control node
      authorized_key:
        user: tempadmin
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        manage_dir: true
      when: tempadmin_check.rc == 1
