- name: Change UID and GID for the ansible user
  hosts: nucs
  become: yes
  vars:
    new_uid: 2000
    new_gid: 2000
  tasks:
    - name: Find current UID 1000 user and GID 1000 group
      command: getent {{ item }}
      with_items:
        - passwd 1000
        - group 1000
      register: getent_results
      changed_when: false
      failed_when: getent_results.rc not in [0, 2]
      check_mode: no
      
    - name: Parse getent output for UID 1000
      set_fact:
        current_uid_1000_user: "{{ getent_results.results[0].stdout.split(':')[0] }}"
        current_gid_1000_group: "{{ getent_results.results[1].stdout.split(':')[0] }}"
      no_log: true
      
    - name: Change UID for the user with UID 1000
      user:
        name: "{{ current_uid_1000_user }}"
        uid: "{{ new_uid }}"
        move_home: true
      when: current_uid_1000_user and current_uid_1000_user != 'dockeruser'

    - name: Change GID for the group with GID 1000
      group:
        name: "{{ current_gid_1000_group }}"
        gid: "{{ new_gid }}"
      when: current_gid_1000_group and current_gid_1000_group != 'dockergroup'
