- name: Set up dockeruser and homelab dependencies
  hosts: nucs
  become: yes
  vars:
    users:
      - username: dockeruser
        uid: 1000
        groups: "dockergroup"
    packages:
      - curl
      - vim
      - git
      - htop
      - nfs-common
      - lm-sensors
      - docker.io
      - docker-compose
  tasks:
    - name: Update the cache and install necessary packages
      apt:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
        cache_valid_time: 3600 # 1 hour

    - name: Ensure the dockeruser is present and has docker group
      user:
        name: "{{ users[0].username }}"
        uid: "{{ users[0].uid }}"
        groups: docker
        append: yes
        system: no

- name: Connect to NAS and prepare for streaming
  hosts: nucs
  become: yes
  tasks:  
    - name: Check if NFS server is reachable
      ping:
        data: "192.168.11.15"
      register: ping_result
      failed_when: ping_result.state != "SUCCESS"

    - name: Set up NFS mounts
      mount:
        path: "/media"
        src: "192.168.11.15:/media"
        fstype: "nfs"
        opts: "defaults"
        state: "mounted"
      when: ping_result.state == "SUCCESS"

    - name: Disable sleep targets
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
        masked: yes
      loop:
        - sleep.target
        - suspend.target
        - hibernate.target
        - hybrid-sleep.target

    - name: Set up BBR for TCP Congestion Control
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      loop:
        - { key: "net.core.default_qdisc", value: "fq" }
        - { key: "net.ipv4.tcp_congestion_control", value: "bbr" }
